packages:
  - 'inlang/source-code/plugins/*'
  - 'inlang/source-code/paraglide/paraglide-js'
  - 'inlang/source-code/sdk'
  - 'inlang/source-code/fink'
  - 'inlang/source-code/cli'
  - 'inlang/source-code/rpc'
  - 'inlang/source-code/website'
  - 'inlang/source-code/website/*'
  - 'inlang/source-code/markdown'
  - 'inlang/source-code/marketplace-manifest'
  - 'inlang/source-code/marketplace-registry'
  - 'inlang/source-code/ui-components/*'
  - 'packages/*'
  - 'packages/*/example'
  - 'packages/*/examples/*'
  