name: Generate Lix API Docs

on:
  push:
    branches:
      - main
    paths:
      - 'packages/lix-sdk/**'
      - '.github/workflows/lix-api-reference.yml'

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm --filter "@lix-sdk..." build
      
      - name: Create API docs
        run: |
          # Create api-docs directory
          mkdir -p packages/lix-sdk/api-docs

      - name: Generate Markdown Documentation
        run: pnpm exec typedoc --out api-docs --plugin typedoc-plugin-markdown --skipErrorChecking ./src
        working-directory: packages/lix-sdk

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add packages/lix-sdk/api-docs/
          git commit -m "Update API docs" || echo "No changes to commit"
          git push